[package]
name = "solagent-rig-goplus"
version = "0.1.2"
edition = "2021"
authors = ["zTgx <beautifularea@gmail.com>"]
repository = "https://github.com/zTgx/solagent.rs"
keywords = ["solagent", "rig", "goplus"]
license = "MIT"
description = "solagent rig goplus"

[dependencies]
solagent-core = "0.1.6"
solagent-plugin-goplus = "0.1.0"
solagent-parameters = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0.9"
