[package]
name = "solagent-rig-rugcheck"
version = "0.1.2"
edition = "2021"
authors = ["zTgx <beautifularea@gmail.com>"]
repository = "https://github.com/zTgx/solagent.rs"
keywords = ["solagent", "rig", "rugcheck"]
license = "MIT"
description = "solagent rig rugcheck"

[dependencies]
solagent-core = "0.1.6"
solagent-parameters = "0.1.0"
solagent-plugin-rugcheck = "0.1.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.9"
serde_json = "1.0"