[package]
name = "solagent-plugin-goplus"
version = "0.1.0"
edition = "2021"
authors = ["zTgx <beautifularea@gmail.com>"]
repository = "https://github.com/zTgx/solagent.rs"
keywords = ["solagent", "plugin", "goplus"]
license = "Apache-2.0"
description = "solagent.rs plugin goplus"

[dependencies]
serde_json = "1.0"
reqwest = { version = "0.12", features = ["json"] }