[package]
name = "birdeye"
version = "0.1.1"
edition = "2021"
rust-version = "1.83.0"

[dependencies]
solagent-core = "0.1.6"
solagent-plugin-birdeye = "0.1.6"
solagent-wallet-solana = "0.1.3"
tokio = { version = "1.42.0", features = ["full"] }
